---
include:
  - project: invenia/gitlab-ci-helper
    file: /templates/python.yml
  - project: invenia/gitlab-ci-helper
    file: /templates/teardown.yml

# teardown.yml will include "Coverage", "Documentation", and "pages"

"Test Python 3.8":
  extends: .test_3_8

"Check Code Format/Typing":
  stage: setup
  extends: .py_3_8
  script:
    - tox -re formatting,types

"Version Check":
  extends: .version_check

"Test PyPI Build":
  extends: .test_dist

"Upload to Private PyPI":
  extends: .upload_to_private_pypi
